version: '3.7'
services:

  diskover:
    image: linuxserver/diskover
    container_name: diskover
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=changeme
      - RUN_ON_START=true
      - USE_CRON=true
    volumes:
      - ${DOCKER_ROOT}/diskover/config:/config
      - ${DISK_1_ROOT}:/data/disk1
      - ${DISK_2_ROOT}:/data/disk2
      - ${USER_ROOT}:/data/yourusername
    ports:
      - ${DISKOVER_WEBUI_PORT}:80
      - 9181:9181
      - 9199:9999
    mem_limit: 4096m
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - redis
    networks: 
      - apps-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.diskover.entrypoints=websecure
      - traefik.http.routers.diskover.rule=Host(`diskover.${DOMAIN}`)
      - traefik.http.routers.diskover.tls.certresolver=myresolver
      - traefik.http.routers.diskover.service=diskover
      - traefik.http.services.diskover.loadbalancer.server.port=80

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    volumes:
      - ${DOCKER_ROOT}/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    networks: 
      - apps-net

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - ${DOCKER_ROOT}/redis:/data
    restart: unless-stopped
    networks: 
      - apps-net

networks: 
  apps-net:
    external: true